# Generated by Django 6.0 on 2025-12-11 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('text', models.TextField(blank=True)),
                ('html_cache', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_commentable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
