# Generated by Django 6.0 on 2025-12-29 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('html_cache', models.TextField(blank=True, null=True)),
                ('is_raw_html', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
