# Generated by Django 6.0 on 2025-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_cache',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_commentable',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
