# Generated by Django 6.0 on 2025-12-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_visible_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
