# Generated by Django 6.0 on 2025-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_html_cache_post_slug_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_raw_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
