# Generated by Django 6.0 on 2025-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_raw_html_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
