# Generated by Django 6.1 on 2026-08-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, default='', help_text='Best 1360x765 px (16:9). The post page shows it 680 px wide. The post list crops it to a centred rectangle.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_image',
            field=models.URLField(blank=True, default='', help_text='Best 1200x630 px (1.91:1) — the standard for Open Graph and for the large Twitter card. Not less than 600x315 px.'),
        ),
    ]
