# Generated by Django 6.0 on 2026-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
