# Generated by Django 6.0 on 2026-01-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created_at',)},
        ),
    ]
