# Generated by Django 6.0.7 on 2026-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_dedupe_likes_by_ip'),
        ('posts', '0004_drop_comments_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_authenticated_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_anonymous_like',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='likes_post_id_063a9e_idx',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'ip_address'), name='unique_like_per_ip'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
